package com.shurjopay.sdk.v2.utils

const val SDK_TYPE_SANDBOX = "sandbox"
const val SDK_TYPE_LIVE = "live"
const val BASE_URL_SANDBOX = "https://sandbox.shurjopayment.com/api/"
const val BASE_URL_LIVE = "https://engine.shurjopayment.com/api/"
const val BASE_URL_IPN_TEST = "http://ipn.shurjotest.com/"
const val BASE_URL_IPN_LIVE = "http://ipn.shurjopay.com/"
const val USER_INPUT_ERROR = "User input error!"
const val PAYMENT_CANCELLED = "Payment has been cancelled!"
const val PAYMENT_DECLINED = "Payment has been declined from gateway!"
const val BANK_TRANSACTION_FAILED = "Bank transaction failed!"
const val NO_INTERNET_PERMISSION = "No internet permission is given!"
const val NO_NETWORK_STATE_PERMISSION = "No network state permission is given!"
const val NO_INTERNET_MESSAGE = "No internet connection! Please check your connection settings."
const val INVALID_AMOUNT = "Invalid amount!"
const val IPN_TEST = "ipn-test"
const val IPN_LIVE = "ipn-live"
const val DATA = "data"
const val SDK_TYPE = "sdk-type"